PFMSproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('finance/', include('finance.urls')),
    path('managerapp/', include('managerapp.urls')),
]

finance/urls.py
from django.urls import path, include
from . import views

app_name = 'finance'


urlpatterns = [
    path('financeHomePage/', views.financeHomepage, name='financeHomePage'),
    path('expense_list/', views.expense_list, name='expense_list'),
    path('budget-alerts/', views.budget_alerts, name='budget_alerts'),
    path('goal_list/', views.goal_list, name='goal_list'),
    path('savings_tracker/', views.savings_tracker, name='savings_tracker'),
    path('settings/', views.settings_profile, name='settings_profile'),
    path('spending_analysis/', views.spending_analysis, name='spending_analysis'),
    path('add_task/', views.add_task, name='add_task'),
    path('<int:pk>/delete/', views.delete_task, name='delete_task'),
    path('emi_calculator/', views.emi_calculator, name='emi_calculator'),

]

managerapp/urls.py
from django.urls import path, include
from . import views

app_name = 'managerapp'


urlpatterns = [
    path('managerhomepage/', views.managerhomepage, name='managerhomepage'),
]

templates/Navbar/ProjectNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">PMFSproject</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'add_contact' %}">Contact Manager</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'feedback' %}">Feedback</a>
        </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'about_us' %}">About us</a>
         </li>

        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
        </li>

      </ul>

    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/Navbar/managerNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Personal Finance Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href=" {% url 'managerapp:managerhomepage' %} ">PFMSproject</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'add_student' %}">Add User</a>
        </li>
            <li class="nav-item">
          <a class="nav-link" href="{% url 'student_list' %}">View User List</a>
        </li>


      </ul>
    </div>
  <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}
 </li>
      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

templates/Navbar/userNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>finance Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href=" {% url 'finance:financeHomePage' %} ">PFMSproject</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'finance:expense_list' %}">Expense Tracking</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'finance:budget_alerts' %}">Budget Watch</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'finance:goal_list' %}">Aspiration Mapping</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'finance:savings_tracker' %}">Savings Tracker</a>
        </li>
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'finance:spending_analysis' %}">Expenditure Review</a>
        </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Smart finance assistant
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'finance:add_task' %}">Reminder</a></li>
            <li><a class="dropdown-item" href="{% url 'finance:emi_calculator' %}">EMI CALCULATOR</a></li>
          </ul>
        </li>
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'finance:settings_profile' %}">Settings</a>
        </li>
      </ul>
    </div>
  <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}
 </li>
      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>